// Code generated by protoc-gen-go.
// source: proto/sync_recognize/sync_recognize.proto
// DO NOT EDIT!

/*
Package google_cloud_speech_v1beta1 is a generated protocol buffer package.

It is generated from these files:
	proto/sync_recognize/sync_recognize.proto

It has these top-level messages:
	SpeechContext
	RecognitionConfig
	RecognitionAudio
	SyncRecognizeRequest
	SpeechRecognitionAlternative
	SpeechRecognitionResult
	SyncRecognizeResponse
*/
package google_cloud_speech_v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RecognitionConfig_AudioEncoding int32

const (
	RecognitionConfig_ENCODING_UNSPECIFIED RecognitionConfig_AudioEncoding = 0
	RecognitionConfig_LINEAR16             RecognitionConfig_AudioEncoding = 1
	RecognitionConfig_FLAC                 RecognitionConfig_AudioEncoding = 2
	RecognitionConfig_MULAW                RecognitionConfig_AudioEncoding = 3
	RecognitionConfig_AMR                  RecognitionConfig_AudioEncoding = 4
	RecognitionConfig_AMR_WB               RecognitionConfig_AudioEncoding = 5
)

var RecognitionConfig_AudioEncoding_name = map[int32]string{
	0: "ENCODING_UNSPECIFIED",
	1: "LINEAR16",
	2: "FLAC",
	3: "MULAW",
	4: "AMR",
	5: "AMR_WB",
}
var RecognitionConfig_AudioEncoding_value = map[string]int32{
	"ENCODING_UNSPECIFIED": 0,
	"LINEAR16":             1,
	"FLAC":                 2,
	"MULAW":                3,
	"AMR":                  4,
	"AMR_WB":               5,
}

func (x RecognitionConfig_AudioEncoding) String() string {
	return proto.EnumName(RecognitionConfig_AudioEncoding_name, int32(x))
}
func (RecognitionConfig_AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type SpeechContext struct {
	Phrases []string `protobuf:"bytes,1,rep,name=phrases" json:"phrases,omitempty"`
}

func (m *SpeechContext) Reset()                    { *m = SpeechContext{} }
func (m *SpeechContext) String() string            { return proto.CompactTextString(m) }
func (*SpeechContext) ProtoMessage()               {}
func (*SpeechContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RecognitionConfig struct {
	Encoding        RecognitionConfig_AudioEncoding `protobuf:"varint,1,opt,name=encoding,enum=google.cloud.speech.v1beta1.RecognitionConfig_AudioEncoding" json:"encoding,omitempty"`
	SampleRate      int32                           `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate" json:"sample_rate,omitempty"`
	LanguageCode    string                          `protobuf:"bytes,3,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
	MaxAlternatives int32                           `protobuf:"varint,4,opt,name=max_alternatives,json=maxAlternatives" json:"max_alternatives,omitempty"`
	ProfanityFilter bool                            `protobuf:"varint,5,opt,name=profanity_filter,json=profanityFilter" json:"profanity_filter,omitempty"`
	SpeechContext   *SpeechContext                  `protobuf:"bytes,6,opt,name=speech_context,json=speechContext" json:"speech_context,omitempty"`
}

func (m *RecognitionConfig) Reset()                    { *m = RecognitionConfig{} }
func (m *RecognitionConfig) String() string            { return proto.CompactTextString(m) }
func (*RecognitionConfig) ProtoMessage()               {}
func (*RecognitionConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RecognitionConfig) GetSpeechContext() *SpeechContext {
	if m != nil {
		return m.SpeechContext
	}
	return nil
}

type RecognitionAudio struct {
	// Types that are valid to be assigned to AudioSource:
	//	*RecognitionAudio_Content
	//	*RecognitionAudio_Uri
	AudioSource isRecognitionAudio_AudioSource `protobuf_oneof:"audio_source"`
}

func (m *RecognitionAudio) Reset()                    { *m = RecognitionAudio{} }
func (m *RecognitionAudio) String() string            { return proto.CompactTextString(m) }
func (*RecognitionAudio) ProtoMessage()               {}
func (*RecognitionAudio) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isRecognitionAudio_AudioSource interface {
	isRecognitionAudio_AudioSource()
}

type RecognitionAudio_Content struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3,oneof"`
}
type RecognitionAudio_Uri struct {
	Uri string `protobuf:"bytes,2,opt,name=uri,oneof"`
}

func (*RecognitionAudio_Content) isRecognitionAudio_AudioSource() {}
func (*RecognitionAudio_Uri) isRecognitionAudio_AudioSource()     {}

func (m *RecognitionAudio) GetAudioSource() isRecognitionAudio_AudioSource {
	if m != nil {
		return m.AudioSource
	}
	return nil
}

func (m *RecognitionAudio) GetContent() []byte {
	if x, ok := m.GetAudioSource().(*RecognitionAudio_Content); ok {
		return x.Content
	}
	return nil
}

func (m *RecognitionAudio) GetUri() string {
	if x, ok := m.GetAudioSource().(*RecognitionAudio_Uri); ok {
		return x.Uri
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RecognitionAudio) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RecognitionAudio_OneofMarshaler, _RecognitionAudio_OneofUnmarshaler, _RecognitionAudio_OneofSizer, []interface{}{
		(*RecognitionAudio_Content)(nil),
		(*RecognitionAudio_Uri)(nil),
	}
}

func _RecognitionAudio_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RecognitionAudio)
	// audio_source
	switch x := m.AudioSource.(type) {
	case *RecognitionAudio_Content:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Content)
	case *RecognitionAudio_Uri:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Uri)
	case nil:
	default:
		return fmt.Errorf("RecognitionAudio.AudioSource has unexpected type %T", x)
	}
	return nil
}

func _RecognitionAudio_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RecognitionAudio)
	switch tag {
	case 1: // audio_source.content
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.AudioSource = &RecognitionAudio_Content{x}
		return true, err
	case 2: // audio_source.uri
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.AudioSource = &RecognitionAudio_Uri{x}
		return true, err
	default:
		return false, nil
	}
}

func _RecognitionAudio_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RecognitionAudio)
	// audio_source
	switch x := m.AudioSource.(type) {
	case *RecognitionAudio_Content:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Content)))
		n += len(x.Content)
	case *RecognitionAudio_Uri:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Uri)))
		n += len(x.Uri)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SyncRecognizeRequest struct {
	Config *RecognitionConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	Audio  *RecognitionAudio  `protobuf:"bytes,2,opt,name=audio" json:"audio,omitempty"`
}

func (m *SyncRecognizeRequest) Reset()                    { *m = SyncRecognizeRequest{} }
func (m *SyncRecognizeRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncRecognizeRequest) ProtoMessage()               {}
func (*SyncRecognizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SyncRecognizeRequest) GetConfig() *RecognitionConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *SyncRecognizeRequest) GetAudio() *RecognitionAudio {
	if m != nil {
		return m.Audio
	}
	return nil
}

type SpeechRecognitionAlternative struct {
	Transcript string  `protobuf:"bytes,1,opt,name=transcript" json:"transcript,omitempty"`
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence" json:"confidence,omitempty"`
}

func (m *SpeechRecognitionAlternative) Reset()                    { *m = SpeechRecognitionAlternative{} }
func (m *SpeechRecognitionAlternative) String() string            { return proto.CompactTextString(m) }
func (*SpeechRecognitionAlternative) ProtoMessage()               {}
func (*SpeechRecognitionAlternative) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SpeechRecognitionResult struct {
	Alternatives []*SpeechRecognitionAlternative `protobuf:"bytes,1,rep,name=alternatives" json:"alternatives,omitempty"`
}

func (m *SpeechRecognitionResult) Reset()                    { *m = SpeechRecognitionResult{} }
func (m *SpeechRecognitionResult) String() string            { return proto.CompactTextString(m) }
func (*SpeechRecognitionResult) ProtoMessage()               {}
func (*SpeechRecognitionResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SpeechRecognitionResult) GetAlternatives() []*SpeechRecognitionAlternative {
	if m != nil {
		return m.Alternatives
	}
	return nil
}

type SyncRecognizeResponse struct {
	Results []*SpeechRecognitionResult `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
}

func (m *SyncRecognizeResponse) Reset()                    { *m = SyncRecognizeResponse{} }
func (m *SyncRecognizeResponse) String() string            { return proto.CompactTextString(m) }
func (*SyncRecognizeResponse) ProtoMessage()               {}
func (*SyncRecognizeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SyncRecognizeResponse) GetResults() []*SpeechRecognitionResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*SpeechContext)(nil), "google.cloud.speech.v1beta1.SpeechContext")
	proto.RegisterType((*RecognitionConfig)(nil), "google.cloud.speech.v1beta1.RecognitionConfig")
	proto.RegisterType((*RecognitionAudio)(nil), "google.cloud.speech.v1beta1.RecognitionAudio")
	proto.RegisterType((*SyncRecognizeRequest)(nil), "google.cloud.speech.v1beta1.SyncRecognizeRequest")
	proto.RegisterType((*SpeechRecognitionAlternative)(nil), "google.cloud.speech.v1beta1.SpeechRecognitionAlternative")
	proto.RegisterType((*SpeechRecognitionResult)(nil), "google.cloud.speech.v1beta1.SpeechRecognitionResult")
	proto.RegisterType((*SyncRecognizeResponse)(nil), "google.cloud.speech.v1beta1.SyncRecognizeResponse")
	proto.RegisterEnum("google.cloud.speech.v1beta1.RecognitionConfig_AudioEncoding", RecognitionConfig_AudioEncoding_name, RecognitionConfig_AudioEncoding_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Speech service

type SpeechClient interface {
	SyncRecognize(ctx context.Context, in *SyncRecognizeRequest, opts ...grpc.CallOption) (*SyncRecognizeResponse, error)
}

type speechClient struct {
	cc *grpc.ClientConn
}

func NewSpeechClient(cc *grpc.ClientConn) SpeechClient {
	return &speechClient{cc}
}

func (c *speechClient) SyncRecognize(ctx context.Context, in *SyncRecognizeRequest, opts ...grpc.CallOption) (*SyncRecognizeResponse, error) {
	out := new(SyncRecognizeResponse)
	err := grpc.Invoke(ctx, "/google.cloud.speech.v1beta1.Speech/SyncRecognize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Speech service

type SpeechServer interface {
	SyncRecognize(context.Context, *SyncRecognizeRequest) (*SyncRecognizeResponse, error)
}

func RegisterSpeechServer(s *grpc.Server, srv SpeechServer) {
	s.RegisterService(&_Speech_serviceDesc, srv)
}

func _Speech_SyncRecognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeechServer).SyncRecognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.speech.v1beta1.Speech/SyncRecognize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeechServer).SyncRecognize(ctx, req.(*SyncRecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Speech_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.speech.v1beta1.Speech",
	HandlerType: (*SpeechServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncRecognize",
			Handler:    _Speech_SyncRecognize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("proto/sync_recognize/sync_recognize.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0xea, 0xe6, 0x6b, 0x92, 0xb4, 0x66, 0x55, 0x84, 0x55, 0x10, 0x20, 0x73, 0x69, 0x91,
	0x30, 0x8a, 0x41, 0x48, 0x48, 0x5c, 0x5c, 0x37, 0x81, 0x48, 0x69, 0x80, 0x8d, 0xaa, 0x72, 0x01,
	0x6b, 0xeb, 0x6c, 0x5c, 0x4b, 0xae, 0xd7, 0x78, 0xd7, 0x51, 0xca, 0x89, 0xff, 0xc2, 0x0f, 0xe1,
	0xaf, 0xb1, 0x5e, 0x37, 0xc5, 0x69, 0xab, 0xa8, 0xb9, 0x65, 0x9e, 0x67, 0xde, 0xcc, 0xbc, 0x79,
	0x59, 0x38, 0x48, 0x52, 0x26, 0xd8, 0x6b, 0x7e, 0x19, 0xfb, 0x5e, 0x4a, 0x7d, 0x16, 0xc4, 0xe1,
	0x2f, 0x7a, 0x23, 0xb4, 0x54, 0x0e, 0x7a, 0x1c, 0x30, 0x16, 0x44, 0xd4, 0xf2, 0x23, 0x96, 0x4d,
	0x2c, 0x9e, 0x50, 0xea, 0x9f, 0x5b, 0xb3, 0xee, 0x19, 0x15, 0xa4, 0x6b, 0x1e, 0x40, 0x67, 0xac,
	0x10, 0x97, 0xc5, 0x82, 0xce, 0x05, 0x32, 0xa0, 0x9e, 0x9c, 0xa7, 0x84, 0x53, 0x6e, 0x54, 0x9e,
	0x6b, 0xfb, 0x4d, 0xbc, 0x08, 0xcd, 0xbf, 0x1a, 0x3c, 0xc0, 0x05, 0xb7, 0x08, 0x59, 0x2c, 0x0b,
	0xa6, 0x61, 0x80, 0xbe, 0x41, 0x83, 0xc6, 0x3e, 0x9b, 0x84, 0x71, 0x20, 0x0b, 0x2a, 0xfb, 0xdb,
	0xf6, 0x07, 0x6b, 0x45, 0x43, 0xeb, 0x16, 0x83, 0xe5, 0x64, 0x93, 0x90, 0xf5, 0xae, 0x38, 0xf0,
	0x35, 0x1b, 0x7a, 0x06, 0x2d, 0x4e, 0x2e, 0x92, 0x88, 0x7a, 0x29, 0x11, 0xd4, 0xd8, 0x94, 0xe4,
	0x55, 0x0c, 0x05, 0x84, 0x25, 0x82, 0x5e, 0x40, 0x27, 0x22, 0x71, 0x90, 0x91, 0x80, 0x7a, 0xb2,
	0x86, 0x1a, 0x9a, 0x4c, 0x69, 0xe2, 0xf6, 0x02, 0x74, 0x25, 0x86, 0x0e, 0x40, 0xbf, 0x20, 0x73,
	0x8f, 0x44, 0x82, 0xa6, 0x31, 0x11, 0xe1, 0x4c, 0x2e, 0xb6, 0xa5, 0xa8, 0x76, 0x24, 0xee, 0x94,
	0xe0, 0x3c, 0x55, 0x2a, 0x36, 0x25, 0x72, 0xba, 0x4b, 0x6f, 0x1a, 0xe6, 0x9f, 0x8c, 0xaa, 0x4c,
	0x6d, 0xe0, 0x9d, 0x6b, 0xbc, 0xaf, 0x60, 0xf4, 0x15, 0xb6, 0x8b, 0xbd, 0x64, 0x63, 0xa5, 0x9b,
	0x51, 0x93, 0x89, 0x2d, 0xfb, 0xe5, 0xca, 0xdd, 0x97, 0x94, 0xc6, 0x1d, 0x5e, 0x0e, 0x4d, 0x02,
	0x9d, 0x25, 0x25, 0xe4, 0x25, 0x76, 0x7b, 0x23, 0xf7, 0xf3, 0xd1, 0x60, 0xf4, 0xd1, 0x3b, 0x19,
	0x8d, 0xbf, 0xf4, 0xdc, 0x41, 0x7f, 0xd0, 0x3b, 0xd2, 0x37, 0x50, 0x1b, 0x1a, 0xc3, 0xc1, 0xa8,
	0xe7, 0xe0, 0xee, 0x3b, 0xbd, 0x82, 0x1a, 0xb0, 0xd5, 0x1f, 0x3a, 0xae, 0xbe, 0x89, 0x9a, 0x50,
	0x3d, 0x3e, 0x19, 0x3a, 0xa7, 0xba, 0x86, 0xea, 0xa0, 0x39, 0xc7, 0x58, 0xdf, 0x42, 0x00, 0x35,
	0xf9, 0xc3, 0x3b, 0x3d, 0xd4, 0xab, 0x26, 0x06, 0xbd, 0x24, 0xbf, 0xea, 0x86, 0xf6, 0xa0, 0xae,
	0x56, 0x88, 0x85, 0x3a, 0x5f, 0xfb, 0xd3, 0x06, 0x5e, 0x00, 0x08, 0x81, 0x96, 0xa5, 0xa1, 0x52,
	0xbe, 0x29, 0xf1, 0x3c, 0x38, 0xdc, 0x86, 0x36, 0xc9, 0x0b, 0x3d, 0xce, 0xb2, 0xd4, 0xa7, 0xe6,
	0x9f, 0x0a, 0xec, 0x8e, 0xa5, 0xed, 0xf0, 0xc2, 0x75, 0x98, 0xfe, 0xcc, 0x28, 0x17, 0xa8, 0x0f,
	0x35, 0x5f, 0x1d, 0x58, 0xf1, 0xb6, 0x6c, 0x6b, 0x3d, 0x5b, 0xe0, 0xab, 0x6a, 0xe4, 0x42, 0x55,
	0x35, 0x54, 0x63, 0xb4, 0xec, 0x57, 0xf7, 0xa5, 0x51, 0xeb, 0xe1, 0xa2, 0xd6, 0xfc, 0x01, 0x4f,
	0x0a, 0xf1, 0xcb, 0x09, 0xff, 0x6f, 0x8f, 0x9e, 0x02, 0x88, 0x94, 0xc4, 0xdc, 0x4f, 0xc3, 0xa4,
	0x10, 0xa2, 0x89, 0x4b, 0x48, 0xfe, 0x5d, 0x8d, 0x33, 0x91, 0xee, 0x2c, 0xac, 0xb8, 0x89, 0x4b,
	0x88, 0x39, 0x87, 0x47, 0xb7, 0xf8, 0x31, 0xe5, 0x59, 0x24, 0xd0, 0x77, 0x29, 0x58, 0xd9, 0x7c,
	0xf9, 0xbf, 0xaa, 0x65, 0xbf, 0xbf, 0x87, 0x51, 0xee, 0x9e, 0x15, 0x2f, 0xd1, 0x99, 0x01, 0x3c,
	0xbc, 0x21, 0x3f, 0x4f, 0x58, 0xcc, 0x29, 0x1a, 0x41, 0x3d, 0x55, 0x13, 0x70, 0x39, 0x6f, 0xde,
	0xf2, 0xed, 0x7a, 0x2d, 0x8b, 0xf1, 0xf1, 0x82, 0xc4, 0xfe, 0x5d, 0x81, 0x5a, 0x91, 0x84, 0x66,
	0xf2, 0xd1, 0x28, 0xf7, 0x44, 0xdd, 0xd5, 0xd4, 0x77, 0xd8, 0x63, 0xcf, 0x5e, 0xa7, 0xa4, 0x58,
	0xe9, 0xac, 0xa6, 0x1e, 0xb4, 0x37, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x6b, 0x91, 0xbc,
	0xfd, 0x04, 0x00, 0x00,
}
